name: "Generate Python Requirements.txt"
description: "Automatically generate requirements.txt for Python projects using pipreqs with smart duplicate handling"
author: "Joerg Heinrich"

inputs:
  PROJECT_PATH:
    description: "Path to the Python project directory to scan for dependencies"
    required: true
    default: "/github/workspace"

  REQUIREMENT_PATH:
    description: "Output path where requirements.txt file should be saved (including filename)"
    required: true
    default: "/github/workspace/requirements.txt"

  RECURSIVE:
    description: "Scan directories recursively for Python files. Set to 'true' or 'false'"
    required: true
    default: "true"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "package"
  color: "blue"
