name: "Automatic requirements.txt for Python Projects"
description: "This action will automatically create the requirements.txt file for a python project using the pipreqs tool."
author: "Ryan Rozario, Joerg Heinrich"

inputs:
  PROJECT_PATH:
    description: "Gives the path of the project"
    required: true
    default: "."

  REQUIREMENT_PATH:
    description: "Folder where requirements.txt has to be saved in"
    required: true
    default: "requirements.txt"

  TOKEN:
    description: "GitHub token to write back to the repository"
    required: true
    default: $GITHUB_TOKEN

  REPOSITORY:
    description: "The repository to use: [organization|user]/[project]"
    required: true

  PROJECT_NAME:
    description: "Name of the project to include in the commit"
    required: true
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "code"
  color: "yellow"
