name: "Generate Python Requirements.txt"
description: "Automatically generates requirements.txt file for Python projects using pipreqs with enhanced duplicate handling and GitHub Actions integration."
author: "Joerg Heinrich"

inputs:
  PROJECT_PATH:
    description: "Gives the path of the project"
    required: true
    default: "/github/workspace"

  REQUIREMENT_PATH:
    description: "Folder where requirements.txt has to be saved in"
    required: true
    default: "/github/workspace/requirements.txt"

  RECURSIVE:
    description: "Collect the requirements recursively, ['true'|'false']; default: 'true'"
    required: true
    default: "true"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "code"
  color: "yellow"
