name: Update README Action Reference
description: "Updates the README file with the latest action tag."
author: "Joerg Heinrich"
branding:
  icon: "file-text"
  color: "green"

inputs:
  README_FILE:
    description: "The path to the README file to update with the latest action tag."
    required: false
    default: "README.md"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: "3.12"

    - name: Update README action reference
      env:
        READMEFILE: ${{ inputs.README_FILE }}
      shell: bash
      run: python .github/actions/update_readme_action_reference/update_readme_action_reference.py
