name: secret_whisperer_dockerhub_registry
description: "This action manages secrets for GitHub Actions workflows."
author: "Joerg Heinrich"

outputs:
  CI_REGISTRY:
    description: "The URL of the CI registry."
    value: ${{ steps.dockerhub-registry-secrets.outputs.secret1 }}
  CI_REGISTRY_USER:
    description: "The username for the CI registry."
    value: ${{ steps.dockerhub-registry-secrets.outputs.secret2 }}
  CI_REGISTRY_PASSWORD:
    description: "The password for the CI registry."
    value: ${{ steps.dockerhub-registry-secrets.outputs.secret3 }}
  CI_REGISTRY_IMAGE_PREFIX:
    description: "The image prefix for the CI registry."
    value: ${{ steps.dockerhub-registry-secrets.outputs.secret4 }}

runs:
  using: "composite"
  steps:
    - name: Get DockerHub Registry Secrets
      id: dockerhub-registry-secrets
      uses: jfheinrich-eu/psono-secret-whisperer@v1.0.0
      with:
        ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
        ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
        ci_server_url: ${{ vars.PSONO_SERVER_URL }}
        secret_id: ${{ secrets.PSONO_DOCKERHUB_REGISTRY_ID }}
        secret_type: "env"
        secret_fields: "CI_REGISTRY,CI_REGISTRY_USER,CI_REGISTRY_PASSWORD,CI_REGISTRY_IMAGE_PREFIX"
        mask_secrets: CI_REGISTRY_USER,CI_REGISTRY_PASSWORD
