name: secret_github_com_token
description: "This action manages secrets for Update Major Tag workflows."
author: "Joerg Heinrich"

inputs:
  PSONO_API_KEY_ID:
    description: "The API key ID for Psono."
    required: true
  PSONO_API_SECRET_KEY_HEX:
    description: "The API secret key in hexadecimal format for Psono."
    required: true
  PSONO_SERVER_URL:
    description: "The URL of the Psono server."
    required: true
  PSONO_GITHUB_COM_TOKEN_ID:
    description: "The ID of the GitHub.com token secret in Psono."
    required: true
outputs:
  GITHUB_COM_TOKEN:
    description: "The GitHub.com token."
    value: ${{ steps.github_com_token.outputs.secret1 }}

runs:
  using: "composite"
  steps:
    - name: Get GITHUB_COM_TOKEN Secrets
      id: github_com_token
      uses: jfheinrich-eu/psono-secret-whisperer@v1.1.0
      with:
        ci_api_key_id: ${{ inputs.PSONO_API_KEY_ID }}
        ci_api_secret_key_hex: ${{ inputs.PSONO_API_SECRET_KEY_HEX }}
        ci_server_url: ${{ inputs.PSONO_SERVER_URL }}
        secret_id: ${{ inputs.PSONO_GITHUB_COM_TOKEN_ID }}
        secret_type: "secret"
        secret_fields: "password"
        mask_secrets: "password"
