name: Daily Report

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 06:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  daily-report:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit
          allowed-endpoints: |
            tech.jfheinrich.eu:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: setup-secrets-gh-token
        name: Setup secrets
        uses: jfheinrich-eu/psono-secret-whisperer@61fb8cf9ca70b1bf0bf832da4af5d8ae7a665613 # v1.0.0
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: ${{ vars.PSONO_SERVER_URL }}
          secret_id: ${{ secrets.PSONO_GITHUB_CLI_TOKEN }}
          secret_type: "secret"
          secret_fields: "password"
          mask_secrets: "password"

      - name: Fetch secrets from Psono
        id: setup-secrets
        uses: jfheinrich-eu/psono-secret-whisperer@61fb8cf9ca70b1bf0bf832da4af5d8ae7a665613 # v1.0.0
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: ${{ vars.PSONO_SERVER_URL }}
          secret_id: ${{ secrets.PSONO_DAILY_REPORT_ACTION_ENV }}
          secret_type: "env"
          secret_fields: "EMAIL_SENDER,EMAIL_USER,EMAIL_RECEIVER,EMAIL_PASSWORD,OPENAI_API_KEY,SMTP_SERVER,SMTP_PORT"
          mask_secrets: "EMAIL_PASSWORD,OPENAI_API_KEY"

      - name: Build and run Daily Report Action
        id: daily_report
        uses: jfheinrich-eu/github-daily-report@663a24d7f86e955e5872a5f5467531703e66b99d # v1.2.2
        with:
          GITHUB_TOKEN: ${{ steps.setup-secrets-gh-token.outputs.secret1 }}
          REPO_NAME: ${{ github.repository }}
          EMAIL_SENDER: ${{ steps.setup-secrets.outputs.secret1 }}
          EMAIL_USER: ${{ steps.setup-secrets.outputs.secret2 }}
          EMAIL_RECEIVER: ${{ steps.setup-secrets.outputs.secret3 }}
          EMAIL_PASSWORD: ${{ steps.setup-secrets.outputs.secret4 }}
          OPENAI_API_KEY: ${{ steps.setup-secrets.outputs.secret5 }}
          SMTP_SERVER: ${{ steps.setup-secrets.outputs.secret6 }}
          SMTP_PORT: ${{ steps.setup-secrets.outputs.secret7 }}

      - name: Create report file with date
        id: create_report_file
        if: steps.daily_report.outputs.report_status == 'success'
        run: |
          echo "Creating report file with date..."
          report_file_name="daily-report-$(date +'%Y-%m-%d').md"
          echo "${{ steps.daily_report.outputs.report }}" > "$report_file_name"
          echo "Report file created: $report_file_name"
          echo "report_file_created=success" >> $GITHUB_OUTPUT
          echo "report_file_name=$report_file_name" >> $GITHUB_OUTPUT
      - name: Upload Daily Report
        if: steps.daily_report.outputs.report_status == 'success' && steps.create_report_file.outputs.report_file_created == 'success'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: daily-report
          path: ${{ steps.create_report_file.outputs.report_file_name }}
