name: Lint
permissions:
  contents: read
  pull-requests: write

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.9"

      - uses: actions/checkout@v4
      - name: Lint
        run: |
          pip install flake8
          cd src && flake8

      - name: Tests
        run: |
          pip install pytest pytest-cov pipreqs
          pytest --cov=github_action.main
