name: Lint
permissions:
  contents: read
  pull-requests: write

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
          pip install -r src/requirements.txt

      - name: Lint
        run: |
          pip install flake8
          cd src && flake8

      - name: Run tests
        run: pytest --cov --cov-branch --cov-report xml:coverage/cov.xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jfheinrich-eu/pipreqs-action
          files: coverage/cov.xml
          verbose: true

      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "coverage/cov.xml"
          send-summary-comment: true
          show-annotations: ''
