name: Lint
permissions:
  contents: read
  pull-requests: write

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: jfheinrich-eu/psono-secret-whisperer@v1.0.0
        id: psono-secrets
        with:
          ci_api_key_id: ${{ secrets.PSONO_API_KEY_ID }}
          ci_api_secret_key_hex: ${{ secrets.PSONO_API_SECRET_KEY_HEX }}
          ci_server_url: ${{ vars.PSONO_SERVER_URL }}
          secret_id: ${{ secrets.PSONO_BARECHECK_ENVIRONMENT }}
          secret_type: 'env'
          secret_fields: 'BARECHECK_GITHUB_APP_TOKEN,API_KEY_PIPREQS_ACTION'
          mask_secrets: 'BARECHECK_GITHUB_APP_TOKEN,API_KEY_PIPREQS_ACTION'

      - uses: jwalton/gh-find-current-pr@v1.3.3
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open          

      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install .
          pip install .[dev]

      - name: Lint
        run: python -m flake8 src

      - name: Run tests
        run: pytest

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: jfheinrich-eu/pipreqs-action
          files: coverage/cov.xml
          verbose: true

      - name: Generate Code Coverage report
        id: code-coverage
        if: success() && steps.findPr.outputs.number
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ steps.psono-secrets.outputs.secret1 }}
          barecheck-api-key: ${{ steps.psono-secrets.outputs.secret2 }}
          lcov-file: "coverage/cov.info"
          pull-number: ${{ steps.findPr.outputs.number }}
          send-summary-comment: true
          show-annotations: 'warning'
